version: '3.8'

name: medidor_agua_ioti_big_data
services:

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin77rd
      MONGO_INITDB_ROOT_PASSWORD: admin1237rd
      MONGO_INITDB_DATABASE: midatabase
    volumes:
      - ./mongo-data:/data/db