server:
  port: 3050
  address: 0.0.0.0
ruta: http://ioti-medidor-agua.app.srvsarcos.net.pe
spring:
  application:
    name: back-medidor-agua
  security:
    user:
      name: renzord
      password: 12345

  data:
    mongodb:
      uri: mongodb://admin77rd:admin1237rd@localhost:27017/midatabase?authSource=admin #mongodb://admin77rd:admin1237rd@161.132.40.211:1234/midatabase?authSource=admin   #mongodb://admin77rd:admin1237rd@localhost:27017/midatabase?authSource=admin  # mongodb://admin77rd:admin1237rd@srv-captain--mongo-ioti:27017/midatabase?authSource=admin
      #mongodb://admin77rd:admin1237rd@localhost:27017/midatabase?authSource=admin #mongodb://admin77rd:admin1237rd@srv-captain--mongo-ioti:27017/midatabase?authSource=admin //    #${SPRING_DATA_MONGODB_URI} #mongodb://admin77rd:admin1237rd@localhost:27017/midatabase?authSource=admin

  #sql:
   # init:
    #  platform: mysql

  #datasource:
   # url: jdbc:mysql://localhost:3306/medidor_db?useSSL=false&serverTimezone=UTC
    #username: root # user create use
    #password:  # modificar contraseña en enetorno de producion

  #jpa:
   # show-sql: true
    #generate-ddl: true
    #database: mysql     # Cambiar POSTGRESQL → mysql
    #properties:
     # hibernate:
      #  ddl-auto: update # Considera cambiar a 'none' o 'validate', 'update', 'create', 'create-drop' en producción
       # format_sql: true


  # Subida de archivos
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

api:
  prefix: /api